language: minimal
services:
- docker
stages:
- build
jobs:
  include:
  - stage: build
    script: docker build -t kubectl:latest .
deploy:
  provider: script
  script: sh build/publish.sh
  on:
    branch: master
env:
  global:
  - secure: XFOXJm08SFnctuluF8raQwcA/gWZ0nefMf+WZ2IC6A8X0NKIR2cxnwQE+6GuvdTNo/UL2gQXaQBkvjBxF/xSM/eP3RUmyn+csvSd8ltw/6jyQSxeBOCr+2NS+appRpGwHznE53tuGql9q1eq3HV7eVNyJjB8vWoRgFdIHykGHMqftYRsFOncjaotRYLi+YKm5PkdVBnkTVS6s3lPgceSoLjkmTSXBY8P0IubDauQublLcMPQBRGCA3B04UFEjzW0NpAwUDp74hKdaOdlXpils7xsDXk3vdeKzUmVSqG0jlFUPr6WdIpJvOSjdJ2/yEACVHCanfNrBMTManxMzLMsajS0GIX4HYpebrRsii5EHg59IlVjGjiI+QJ5dyEDG6sJOVW+McbMqSXq84zc7yhhy7D6zwfaFg3bHykpXIDwJeZnsMRQQyftnDaclgJpqSE4jylUtb424N+ZjSXoXWglaP+6z3/QVyJd3BxIEJRECarUGw7oq/f3Jdx05JipdVnyiDBzJntBMbMwICLMSisdWZ/bOOB2/1aAXBYUZXC6lDhb/rzuLniKO1ZqU6tGydVGbIsiY44AAxlLQYTRBukEPYTxyaVYcaX/xjFMhX44J6RoMC95kX0DswnNts6LCfWbzCwbp6kdnrnioRHVh+q2v6VzoClqLm7UxvZQW0pW8l0=
  - secure: eUh7ZoDywU4am5cbHY76KPbnOiTD4y8JHl+/mTySnPZU5D6xJIIBLLyizk51uWbAMi6oMY31V+0uVKFDMWxg9IvrCtCYm5iLlaFaJGG9SsRPbCle29s7q26t3Pk7/RNs17qEUKnGW1TFRW6C0QiraVAAIi9s/livCD4Lyzi+LkTHf0VBxKihw8n4s/mSeSzBBe22L2QT0HcMxfz+FvwQspOKjnYErQ+NIltZz6RvpP9QNa9xbg7cmsUnA/X2mpXtGhjPfkhe0Fuf3XZkAMxJe/rn3H2/X6pYHYFQk/g5R7QJNsYksQlMbtbvBATxg9GoUJtNd0OXimi1niE5wCWPB7jhcjSuEfHoadDrjZ3zPzsfcT1MivP6FyoWiP0RktNYICifZ0UpNLD9qiwxsVvAxAcXC8V/MfCsR/ZKkXSKc9llP/svTSyEhnTxdQ81XCNOzebT5I1OlPvK/7Q6WJPjKLVgnPrW8sGEira/wjuWV96lwtdLNpvdPL7nOSIAEnJav5vdp7hPzeCj8Zim0AwA+vGhVCv1WkSOyMTNLme/5BjzTK8lyeDsYb3MKtm1N9u9yEs7DIlbRi9u/nrENHPffAzbFxnCqbY+xn0m2KwEDwo/+8rigl26bMzdHYZFbyPzFVWoJrFNdgOYIarkd52ikIu3O2zgLT3d11CPjJoODVU=
