language: minimal

services:
- docker

stages:
- build

jobs: 
  include:
  - stage: build
    script: docker build -t kubectl:latest .
deploy:
  provider: script
  script: sh docker_push.sh
  secure: "TwJbbBqTulywlcXtTmrJQYE0xWbP0A2i4/V1feTEYaOB4IGLJbz3wIMFiZ34g9yVkviX+TFEuQ6S2LgYUMxIGZE5ufW1mcD7eAjt7wyTiqEVbvIcFeGG19OldC8j2Vr+A7bVzEc5W614e4N+fQGFPmd7Ze0hX7L7P8HNLY7c5j764CCbzZWysUFNf6RID+n3erHGgdlbVItR/5BwlJ53pwo3zm2MYT3Mt7G9/uAqoEgHdbktY9diKAJxphlJ++15F+MNypgb0Y6ZwVCjkA3q1LOHNZ+Q4VGek063g8TjeoZmlyLxomxNisqQTspbw2vqYlqGY7SK8RCeXGmhANwJAjZPXJyE3xlxAkYax+HD5TLdwzLFfS87VRZHxsR5oBmfV0AYEu3c9JJIGfHrFtdI8xTG7Fa7CxHYmi6ERdOsanpoHcaZqCw1UU9rySCs+mrlX8MLY7QzFFokM447poAVcQhd6GpzoaP1YfNtS8Cfk0hVuS0EEE+CkAp9TuXZixkoerwDSCte6yoYj2d6oq1wPCfjBBAwKVyCvVNza7MkjmXrhMcahH1GDv6DiKWq1R+3q46C7Z53SF6fq4aEqcMHo1GraCwHzMyicj/Te0Ew1kZsmU4FqUMF2xTIoH90TU1YJUBNUOpL8nYFtrE9SQ/BVwt7FXzpTGn56zcqhgjcfbw="
  secure: "mt+NJNUzP6VRlTUCRx50ERD3zpfk2c97F0IFYmtsposyixq8vU1jYOFzrggJZMItvq69EOhPQwzrxX2UDYri0IirZ3iVLIJXruW7/va8v3sjobyHb5QxrrAEt6dnE7IbqQT7AUGTO0Lz9wuvKpdItFp1PNZVHoTKcOSNdxUq5rkHFCFG+T01CAwggK9o9DRst3GN3+1fLVAJwb6Gy1IfGluez/xwDASzvoXBUCjcx88yMj6HTwn3om99eLtH1kC8IVN0XE8+CJ4ZUg60R2aGji32xSroQZQgyL6MxCOxfa3+L0sEdAskQsSkQhkoRfFdp22uIJrqdnjjU945PgNl5W/UWDFJvc4iQZxG7TSuMlBB4bG9jU46V005kKJ0FUS54PwAUacRicmHZw1eJjMMVhAPSS81a93vmqFJwz5QrXgrSbxANW3nX9DeAYilS7/KN57txBO/QDUiuAFsL2Q6aRQfq00TLnTGbHkG4tyI5VweMJ7WMXNHplmrqyk95OXJJgbT1f04tsJuTKFTXgx4PuNuX1mKfV73suGHGvQOaQSUO+U9LGkMVzSNbhzcWpvm7XX1tpv7VupCjl7j//sR7VHIV1adAKRkeGijxk3TUu5GG1H0nkdCQfKIsgcfWI5KgXRZic5gw7/UlYG1Ls8CtwL1IovixQ3s/Ff3WHb1vmc="
  on:
    branch: master
